apiVersion: v1
kind: Secret
metadata:
  name: postgres-config
  namespace: todo-app
type: Opaque
data:
  POSTGRES_USER: bXl1c2Vy            # base64 encoded 'myuser'
  POSTGRES_PASSWORD: bXlwYXNzd29yZA==  # base64 encoded 'mypassword'
  POSTGRES_DB: bXlkYg==              # base64 encoded 'mydb'
  DATABASE_URL: cG9zdGdyZXNxbDovL215dXNlcjpteXBhc3N3b3JkQHBvc3RncmVzOjU0MzIvbXlkYg==  # base64 encoded 'postgresql://myuser:mypassword@postgres:5432/mydb'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: todo-app
data:
  PORT: "3001" 