# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - mrtkek-dev-we-fe

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://docker.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_01296a1885f240dcae1751ad5b4ce32b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_1e036c4981974a8abdf28dea854f730b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: docker.io/${{ secrets.AzureAppService_ContainerUsername_01296a1885f240dcae1751ad5b4ce32b }}/nginx:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'mrtkek-dev-we-fe'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_bf08a492d57249509a9adfa7d6442f7f }}
        images: 'docker.io/${{ secrets.AzureAppService_ContainerUsername_01296a1885f240dcae1751ad5b4ce32b }}/nginx:${{ github.sha }}'